import React, { useState, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import ExportButton from '../components/ExportButton'

// Initial Pre-populated campaigns data
const initialCampaigns = [
  {
    id: 'CMP-001',
    name: 'Google Ads - B.Tech Admissions 2026',
    type: 'Google Ads',
    source: 'Google Ads API',
    status: 'ACTIVE',
    startDate: '2026-04-01',
    endDate: '2026-07-31',
    budget: 15000,
    leads: 840,
    qualifiedLeads: 620,
    convertedLeads: 120,
    owner: 'John Doe (Self)',
    description: 'Targeted keyword search campaign for prospective Engineering students.',
    mapping: 'Website Form & Landing Page',
    assignment: 'Round Robin Distribution'
  },
  {
    id: 'CMP-002',
    name: 'Meta Ads - MBA Lookalike Inquiries',
    type: 'Facebook Ads',
    source: 'Facebook Lead Form',
    status: 'ACTIVE',
    startDate: '2026-04-05',
    endDate: '2026-06-30',
    budget: 12000,
    leads: 710,
    qualifiedLeads: 490,
    convertedLeads: 85,
    owner: 'Jane Smith',
    description: 'Lookalike audience advertising focusing on corporate managers.',
    mapping: 'Facebook API',
    assignment: 'Auto Assign to Sales Team A'
  },
  {
    id: 'CMP-003',
    name: 'WhatsApp - Q3 Executive MBA Outreach',
    type: 'WhatsApp Campaign',
    source: 'API Integration',
    status: 'PAUSED',
    startDate: '2026-04-10',
    endDate: '2026-05-30',
    budget: 3500,
    leads: 320,
    qualifiedLeads: 210,
    convertedLeads: 45,
    owner: 'John Doe (Self)',
    description: 'Bulk chat messaging funnel pointing to enrollment calendars.',
    mapping: 'API Webhook',
    assignment: 'Manual Assignment'
  },
  {
    id: 'CMP-004',
    name: 'Email - Scholarship Admissions Drive',
    type: 'Email Marketing',
    source: 'Landing Page',
    status: 'ACTIVE',
    startDate: '2026-04-12',
    endDate: '2026-08-31',
    budget: 2500,
    leads: 1100,
    qualifiedLeads: 820,
    convertedLeads: 195,
    owner: 'Jane Smith',
    description: 'Weekly scholarship newsletters targeting alumni list dropouts.',
    mapping: 'Website Form',
    assignment: 'Auto Assign to Sales Team B'
  },
  {
    id: 'CMP-005',
    name: 'Webinar - Virtual Campus Fair Outreach',
    type: 'Webinar',
    source: 'Landing Page',
    status: 'COMPLETED',
    startDate: '2026-03-01',
    endDate: '2026-03-25',
    budget: 4500,
    leads: 480,
    qualifiedLeads: 310,
    convertedLeads: 58,
    owner: 'Alex Johnson',
    description: 'Admissions open house virtual webinar tracking.',
    mapping: 'Landing Page Integration',
    assignment: 'Round Robin Distribution'
  }
]

// Mock leads list generated by campaigns for details view
const initialLeadsList = [
  { id: 'LD-101', name: 'Alice Cooper', email: 'alice@example.com', status: 'Converted', source: 'Google Ads', campaignId: 'CMP-001', assignedTo: 'Sales Team A' },
  { id: 'LD-102', name: 'Bob Marley', email: 'bob@example.com', status: 'Qualified', source: 'Google Ads', campaignId: 'CMP-001', assignedTo: 'Sales Team A' },
  { id: 'LD-103', name: 'Charlie Puth', email: 'charlie@example.com', status: 'Contacted', source: 'Google Ads', campaignId: 'CMP-001', assignedTo: 'Sales Team B' },
  { id: 'LD-104', name: 'Diana Ross', email: 'diana@example.com', status: 'New', source: 'Facebook Lead Form', campaignId: 'CMP-002', assignedTo: 'Sales Team B' },
  { id: 'LD-105', name: 'Elvis Presley', email: 'elvis@example.com', status: 'Converted', source: 'Facebook Lead Form', campaignId: 'CMP-002', assignedTo: 'Sales Team A' },
  { id: 'LD-106', name: 'Fiona Apple', email: 'fiona@example.com', status: 'Lost', source: 'API Integration', campaignId: 'CMP-003', assignedTo: 'Unassigned' }
]

// Mock activities log for campaign details
const initialActivities = [
  { id: 1, campaignId: 'CMP-001', date: '2026-05-20', time: '11:42', type: 'Update', user: 'John Doe', text: 'Daily Google Ads budget increased by $50 to support summer keywords.' },
  { id: 2, campaignId: 'CMP-001', date: '2026-05-18', time: '09:15', type: 'Note', user: 'Jane Smith', text: 'Google Analytics tracking verified. Goal conversions sync perfectly.' },
  { id: 3, campaignId: 'CMP-002', date: '2026-05-15', time: '14:30', type: 'Task', user: 'Jane Smith', text: 'Ad creative carousel refreshed with new testimonial photos.' }
]

export default function Campaigns() {
  // Top Navigation View Switcher: 'DASHBOARD' | 'ALL_CAMPAIGNS' | 'CREATE_CAMPAIGN' | 'DETAILS' | 'REPORTS'
  const [activeTab, setActiveTab] = useState('DASHBOARD')

  // Campaigns list state
  const [campaigns, setCampaigns] = useState(initialCampaigns)
  const [selectedCampaignId, setSelectedCampaignId] = useState('CMP-001')

  // Details Tab Sub-View: 'OVERVIEW' | 'LEADS' | 'ACTIVITIES' | 'ANALYTICS'
  const [detailsSubTab, setDetailsSubTab] = useState('OVERVIEW')

  // Filter States (All Campaigns tab)
  const [filterType, setFilterType] = useState('ALL')
  const [filterStatus, setFilterStatus] = useState('ALL')
  const [searchTerm, setSearchTerm] = useState('')

  // Create Campaign Form State
  const [newCampaign, setNewCampaign] = useState({
    name: '',
    description: '',
    type: 'Facebook Ads',
    sources: ['Website'],
    owner: 'John Doe (Self)',
    startDate: new Date().toISOString().split('T')[0],
    endDate: '',
    budget: 5000,
    mapping: 'Website',
    assignment: 'Round Robin Distribution'
  })

  // Activities logger state
  const [activities, setActivities] = useState(initialActivities)
  const [newNote, setNewNote] = useState('')

  // Toast
  const [toastMsg, setToastMsg] = useState(null)

  const triggerToast = (msg) => {
    setToastMsg(msg)
    setTimeout(() => setToastMsg(null), 3000)
  }

  // Active Campaign Object
  const activeCampaign = useMemo(() => {
    return campaigns.find(c => c.id === selectedCampaignId) || campaigns[0]
  }, [campaigns, selectedCampaignId])

  // Calculated Aggregate Stats
  const aggregateStats = useMemo(() => {
    const total = campaigns.length
    const active = campaigns.filter(c => c.status === 'ACTIVE').length
    const completed = campaigns.filter(c => c.status === 'COMPLETED').length
    const leads = campaigns.reduce((sum, c) => sum + c.leads, 0)
    const qualified = campaigns.reduce((sum, c) => sum + c.qualifiedLeads, 0)
    const converted = campaigns.reduce((sum, c) => sum + c.convertedLeads, 0)
    const budget = campaigns.reduce((sum, c) => sum + c.budget, 0)

    const conversionRate = leads > 0 ? (converted / leads) * 100 : 0
    const cpl = leads > 0 ? budget / leads : 0

    return { total, active, completed, leads, qualified, converted, budget, conversionRate, cpl }
  }, [campaigns])

  // All Campaigns Filtering Logic
  const filteredCampaigns = useMemo(() => {
    return campaigns.filter(c => {
      const matchesSearch = c.name.toLowerCase().includes(searchTerm.toLowerCase()) || c.owner.toLowerCase().includes(searchTerm.toLowerCase())
      const matchesType = filterType === 'ALL' || c.type === filterType
      const matchesStatus = filterStatus === 'ALL' || c.status === filterStatus
      return matchesSearch && matchesType && matchesStatus
    })
  }, [campaigns, searchTerm, filterType, filterStatus])

  // Handle Campaign Duplication
  const handleDuplicateCampaign = (c) => {
    const duplicated = {
      ...c,
      id: `CMP-${Math.floor(100 + Math.random() * 900)}`,
      name: `${c.name} (Copy)`,
      status: 'DRAFT',
      leads: 0,
      qualifiedLeads: 0,
      convertedLeads: 0
    }
    setCampaigns([...campaigns, duplicated])
    triggerToast(`Duplicated campaign as "${duplicated.name}"!`)
  }

  // Handle Campaign Delete
  const handleDeleteCampaign = (id) => {
    setCampaigns(campaigns.filter(c => c.id !== id))
    triggerToast('Campaign deleted successfully.')
  }

  // Handle Create Campaign Submission
  const handleCreateCampaign = (e) => {
    e.preventDefault()
    if (!newCampaign.name.trim()) return

    const created = {
      id: `CMP-${Math.floor(100 + Math.random() * 900)}`,
      ...newCampaign,
      mapping: newCampaign.sources && newCampaign.sources.length > 0 ? newCampaign.sources.join(', ') : 'None',
      budget: Number(newCampaign.budget) || 1000,
      status: 'ACTIVE',
      leads: 0,
      qualifiedLeads: 0,
      convertedLeads: 0
    }

    setCampaigns([created, ...campaigns])
    setActiveTab('ALL_CAMPAIGNS')
    triggerToast(`Campaign "${created.name}" created and mapped successfully!`)
  }

  // Handle add activity log/note
  const handleAddActivity = (e) => {
    e.preventDefault()
    if (!newNote.trim()) return

    const note = {
      id: activities.length + 1,
      campaignId: activeCampaign.id,
      date: new Date().toISOString().split('T')[0],
      time: new Date().toTimeString().slice(0, 5),
      type: 'Note',
      user: 'John Doe',
      text: newNote
    }

    setActivities([note, ...activities])
    setNewNote('')
    triggerToast('Note added to activities log.')
  }

  return (
    <div className="w-full relative h-full flex flex-col font-sans select-none bg-[#f8fafc] p-6 space-y-6 overflow-y-auto">
      
      {/* Toast */}
      <AnimatePresence>
        {toastMsg && (
          <motion.div
            initial={{ opacity: 0, y: -20, x: '-50%' }}
            animate={{ opacity: 1, y: 0, x: '-50%' }}
            exit={{ opacity: 0, y: -20, x: '-50%' }}
            className="fixed top-6 left-1/2 z-50 bg-slate-900 text-white px-4 py-2.5 rounded-lg shadow-xl border border-slate-800 flex items-center gap-2 text-xs font-bold font-sans"
          >
            <span className="material-symbols-outlined text-[16px] text-green-400">check_circle</span>
            {toastMsg}
          </motion.div>
        )}
      </AnimatePresence>

      {/* TOP NAVIGATION BAR */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs">
        <div className="text-left">
          <span className="text-[10px] font-extrabold text-blue-600 uppercase tracking-widest block mb-0.5">Campaign Module</span>
          <h1 className="text-xl font-extrabold text-slate-800">Campaign Management</h1>
          <p className="text-[11.5px] text-slate-400 font-medium mt-0.5">Blend of Salesforce and HubSpot features: generate leads, configure tracking forms, assign rules, and generate reports.</p>
        </div>
        <div className="flex flex-wrap bg-slate-50 border border-slate-200 rounded-xl p-1 gap-0.5">
          {[
            { id: 'DASHBOARD', label: 'Dashboard', icon: 'dashboard' },
            { id: 'ALL_CAMPAIGNS', label: 'All Campaigns', icon: 'campaign' },
            { id: 'CREATE_CAMPAIGN', label: 'Create Campaign', icon: 'add_circle' },
            { id: 'DETAILS', label: 'Details', icon: 'feed' },
            { id: 'REPORTS', label: 'Reports', icon: 'assessment' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id)
                if (tab.id === 'DETAILS' && !selectedCampaignId) {
                  setSelectedCampaignId(campaigns[0]?.id || '')
                }
              }}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer ${
                activeTab === tab.id
                  ? 'bg-white shadow-2xs text-blue-600 font-extrabold border border-slate-250/50'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <span className="material-symbols-outlined text-[14px]">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* VIEW CONDITIONAL RENDERING */}
      <div className="w-full">
        {activeTab === 'DASHBOARD' && (
          <div className="space-y-6">
            {/* KPI Metrics deck */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-left">
              <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-2xs">
                <span className="text-[10px] font-bold text-slate-450 uppercase tracking-wider block">Total / Active Campaigns</span>
                <span className="text-xl font-black text-slate-800 block mt-1">{aggregateStats.total} / {aggregateStats.active} Active</span>
                <span className="text-[9.5px] text-slate-400 block mt-1">Total program budgets: ${aggregateStats.budget.toLocaleString()}</span>
              </div>
              <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-2xs">
                <span className="text-[10px] font-bold text-slate-450 uppercase tracking-wider block">Total Leads Generated</span>
                <span className="text-xl font-black text-slate-800 block mt-1">+{aggregateStats.leads.toLocaleString()}</span>
                <span className="text-[9.5px] text-slate-400 block mt-1">Conversion: {aggregateStats.conversionRate.toFixed(1)}%</span>
              </div>
              <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-2xs">
                <span className="text-[10px] font-bold text-slate-450 uppercase tracking-wider block">Qualified Leads</span>
                <span className="text-xl font-black text-indigo-700 block mt-1">+{aggregateStats.qualified.toLocaleString()}</span>
                <span className="text-[9.5px] text-slate-400 block mt-1">Vetting Rate: {((aggregateStats.qualified / aggregateStats.leads) * 100).toFixed(0)}%</span>
              </div>
              <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-2xs">
                <span className="text-[10px] font-bold text-slate-450 uppercase tracking-wider block">Cost Per Lead (CPL)</span>
                <span className="text-xl font-black text-green-600 block mt-1">${aggregateStats.cpl.toFixed(2)}</span>
                <span className="text-[9.5px] text-slate-400 block mt-1">Average budget efficiency scale</span>
              </div>
            </div>

            {/* Performance charts section */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 text-left">
              {/* Funnel pipeline */}
              <div className="lg:col-span-2 bg-white border border-slate-200 rounded-2xl p-5 shadow-2xs space-y-4">
                <h3 className="text-sm font-bold text-slate-800">Master Conversion Lifecycle Funnel</h3>
                
                <div className="space-y-3">
                  {[
                    { stage: 'Total Leads Ingested', val: aggregateStats.leads, pct: 100, color: 'bg-blue-500' },
                    { stage: 'Marketing Qualified Leads (MQL)', val: aggregateStats.qualified, pct: (aggregateStats.qualified / aggregateStats.leads) * 100, color: 'bg-indigo-500' },
                    { stage: 'Converted Enrollments', val: aggregateStats.converted, pct: (aggregateStats.converted / aggregateStats.leads) * 100, color: 'bg-green-600' }
                  ].map((f, i) => (
                    <div key={i} className="space-y-1">
                      <div className="flex justify-between text-xs font-semibold text-slate-650">
                        <span>{f.stage}</span>
                        <span>{f.val} ({f.pct.toFixed(0)}%)</span>
                      </div>
                      <div className="h-3 bg-slate-100 rounded-full overflow-hidden">
                        <div className={`h-full ${f.color} rounded-full`} style={{ width: `${f.pct}%` }}></div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Source breakdown */}
              <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-2xs space-y-3">
                <h3 className="text-sm font-bold text-slate-800">Platform Share</h3>
                <div className="space-y-2 pt-2">
                  {[
                    { source: 'Google Ads', share: 45, color: 'bg-blue-650' },
                    { source: 'Meta / Facebook Ads', share: 30, color: 'bg-indigo-650' },
                    { source: 'Email Campaigns', share: 15, color: 'bg-purple-650' },
                    { source: 'WhatsApp / Other', share: 10, color: 'bg-emerald-650' }
                  ].map((s, i) => (
                    <div key={i} className="flex justify-between items-center text-xs">
                      <div className="flex items-center gap-2">
                        <span className={`w-2.5 h-2.5 rounded-full ${s.color}`}></span>
                        <span className="font-semibold text-slate-700">{s.source}</span>
                      </div>
                      <strong className="text-slate-800">{s.share}%</strong>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'ALL_CAMPAIGNS' && (
          <div className="space-y-4">
            
            {/* SEARCH AND FILTERS */}
            <div className="flex flex-col sm:flex-row justify-between items-stretch sm:items-center gap-3 bg-white p-4 border border-slate-200 rounded-2xl shadow-2xs text-left">
              <div className="relative flex-1">
                <span className="material-symbols-outlined text-[16px] text-slate-400 absolute left-3 top-1/2 -translate-y-1/2">search</span>
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Search by campaign name or owner..."
                  className="w-full h-8.5 pl-9 pr-3 border border-slate-200 rounded-xl bg-slate-50 text-[11.5px] outline-none focus:bg-white focus:border-blue-500"
                />
              </div>

              <div className="flex gap-2">
                <select
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value)}
                  className="h-8.5 px-3 border border-slate-200 rounded-xl bg-slate-50 text-[11px] font-bold outline-none cursor-pointer hover:bg-slate-100 transition-colors"
                >
                  <option value="ALL">All Types</option>
                  <option value="Google Ads">Google Ads</option>
                  <option value="Facebook Ads">Facebook Ads</option>
                  <option value="Email Marketing">Email Marketing</option>
                  <option value="WhatsApp Campaign">WhatsApp</option>
                  <option value="Webinar">Webinar</option>
                </select>

                <select
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value)}
                  className="h-8.5 px-3 border border-slate-200 rounded-xl bg-slate-50 text-[11px] font-bold outline-none cursor-pointer hover:bg-slate-100 transition-colors"
                >
                  <option value="ALL">All Statuses</option>
                  <option value="ACTIVE">ACTIVE</option>
                  <option value="PAUSED">PAUSED</option>
                  <option value="COMPLETED">COMPLETED</option>
                  <option value="DRAFT">DRAFT</option>
                </select>
              </div>
            </div>

            {/* CAMPAIGN LIST TABLE */}
            <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-2xs text-left">
              <table className="w-full min-w-[950px] border-collapse">
                <thead>
                  <tr className="border-b border-slate-200 bg-slate-50/50 text-[11px] font-bold text-slate-500 uppercase tracking-wider select-none text-center">
                    <th className="px-5 py-3 text-left w-64">Campaign Details</th>
                    <th className="px-5 py-3 w-28">Type</th>
                    <th className="px-5 py-3 w-24">Status</th>
                    <th className="px-5 py-3 w-32">Timeline</th>
                    <th className="px-5 py-3 w-24">Leads</th>
                    <th className="px-5 py-3 w-24">Qualified</th>
                    <th className="px-5 py-3 w-24">Converted</th>
                    <th className="px-5 py-3 w-28">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-150 text-[12.5px] font-sans">
                  {filteredCampaigns.map((c) => (
                    <tr key={c.id} className="hover:bg-slate-50/30 transition-colors">
                      <td className="px-5 py-3">
                        <span
                          onClick={() => { setSelectedCampaignId(c.id); setActiveTab('DETAILS'); }}
                          className="font-bold text-slate-800 hover:underline cursor-pointer block"
                        >
                          {c.name}
                        </span>
                        <span className="text-[10px] text-slate-400 font-semibold block mt-0.5">Owner: {c.owner} • Budget: ${c.budget.toLocaleString()}</span>
                      </td>
                      <td className="px-5 py-3 text-center text-slate-650 font-semibold">{c.type}</td>
                      <td className="px-5 py-3 text-center">
                        <span className={`inline-block px-2 py-0.5 rounded text-[9.5px] font-extrabold border ${
                          c.status === 'ACTIVE' ? 'bg-green-50 border-green-200 text-green-700' :
                          c.status === 'PAUSED' ? 'bg-amber-50 border-amber-200 text-amber-700' :
                          c.status === 'COMPLETED' ? 'bg-blue-50 border-blue-200 text-blue-700' :
                          'bg-slate-100 border-slate-200 text-slate-500'
                        }`}>{c.status}</span>
                      </td>
                      <td className="px-5 py-3 text-center text-slate-500 font-mono text-[11px]">{c.startDate} to {c.endDate || 'Ongoing'}</td>
                      <td className="px-5 py-3 text-center font-mono font-bold text-slate-800">+{c.leads}</td>
                      <td className="px-5 py-3 text-center font-mono font-bold text-indigo-600">+{c.qualifiedLeads}</td>
                      <td className="px-5 py-3 text-center font-mono font-bold text-green-600">+{c.convertedLeads}</td>
                      <td className="px-5 py-3 text-center select-none">
                        <div className="flex justify-center gap-1.5">
                          <button
                            onClick={() => { setSelectedCampaignId(c.id); setActiveTab('DETAILS'); }}
                            className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                            title="View Overview"
                          >
                            <span className="material-symbols-outlined text-[15px] block">visibility</span>
                          </button>
                          <button
                            onClick={() => handleDuplicateCampaign(c)}
                            className="p-1 text-purple-650 hover:bg-purple-50 rounded"
                            title="Duplicate"
                          >
                            <span className="material-symbols-outlined text-[15px] block">content_copy</span>
                          </button>
                          <button
                            onClick={() => handleStatusToggle(c.id)}
                            className="p-1 text-amber-600 hover:bg-amber-50 rounded"
                            title="Pause/Resume"
                          >
                            <span className="material-symbols-outlined text-[15px] block">pause_circle</span>
                          </button>
                          <button
                            onClick={() => handleDeleteCampaign(c.id)}
                            className="p-1 text-red-600 hover:bg-red-50 rounded"
                            title="Delete"
                          >
                            <span className="material-symbols-outlined text-[15px] block">delete</span>
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

          </div>
        )}

        {activeTab === 'CREATE_CAMPAIGN' && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs max-w-2xl mx-auto text-left">
            <h2 className="text-md font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">Create New Campaign</h2>
            <form onSubmit={handleCreateCampaign} className="space-y-4">
              
              {/* Name & Owner */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Campaign Name *</label>
                  <input
                    type="text"
                    required
                    value={newCampaign.name}
                    onChange={(e) => setNewCampaign({ ...newCampaign, name: e.target.value })}
                    placeholder="e.g. Meta Q3 Admissions Drive"
                    className="w-full h-8 px-2.5 border border-slate-200 rounded-lg bg-slate-50 text-[11.5px] focus:bg-white focus:border-blue-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Campaign Owner</label>
                  <input
                    type="text"
                    value={newCampaign.owner}
                    onChange={(e) => setNewCampaign({ ...newCampaign, owner: e.target.value })}
                    className="w-full h-8 px-2.5 border border-slate-200 rounded-lg bg-slate-50 text-[11.5px] focus:bg-white focus:border-blue-500 outline-none"
                  />
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Description</label>
                <textarea
                  value={newCampaign.description}
                  onChange={(e) => setNewCampaign({ ...newCampaign, description: e.target.value })}
                  placeholder="Summarize campaigns goal and targeting setup..."
                  className="w-full p-2 border border-slate-200 rounded-lg bg-slate-50 text-[11.5px] focus:bg-white focus:border-blue-500 outline-none resize-none"
                  rows="2"
                />
              </div>

              {/* Type, Budget & Date Range */}
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Campaign Type</label>
                  <select
                    value={newCampaign.type}
                    onChange={(e) => setNewCampaign({ ...newCampaign, type: e.target.value })}
                    className="w-full h-8 px-2 border border-slate-200 rounded-lg bg-slate-50 text-[11px] font-bold outline-none cursor-pointer"
                  >
                    <option value="Facebook Ads">Facebook Ads</option>
                    <option value="Google Ads">Google Ads</option>
                    <option value="Email Marketing">Email Marketing</option>
                    <option value="WhatsApp Campaign">WhatsApp Campaign</option>
                    <option value="SMS Campaign">SMS Campaign</option>
                    <option value="Webinar">Webinar</option>
                    <option value="Event">Event</option>
                    <option value="Referral Campaign">Referral Campaign</option>
                    <option value="Organic Marketing">Organic Marketing</option>
                    <option value="Other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Budget ($)</label>
                  <input
                    type="number"
                    value={newCampaign.budget}
                    onChange={(e) => setNewCampaign({ ...newCampaign, budget: e.target.value })}
                    className="w-full h-8 px-2.5 border border-slate-200 rounded-lg bg-slate-50 text-[11.5px] focus:bg-white focus:border-blue-500 outline-none font-bold"
                  />
                </div>
                <div>
                  <label className="text-[10px] font-extrabold text-slate-400 block mb-1 uppercase tracking-wider">Date Range</label>
                  <div className="flex gap-1.5">
                    <input
                      type="date"
                      value={newCampaign.startDate}
                      onChange={(e) => setNewCampaign({ ...newCampaign, startDate: e.target.value })}
                      className="w-1/2 h-8 px-1.5 border border-slate-200 rounded-lg bg-slate-50 text-[10px] font-medium outline-none"
                    />
                    <input
                      type="date"
                      value={newCampaign.endDate}
                      onChange={(e) => setNewCampaign({ ...newCampaign, endDate: e.target.value })}
                      className="w-1/2 h-8 px-1.5 border border-slate-200 rounded-lg bg-slate-50 text-[10px] font-medium outline-none"
                    />
                  </div>
                </div>
              </div>

              {/* Lead Sources Selection */}
              <div>
                <label className="text-[10px] font-extrabold text-slate-400 block mb-1.5 uppercase tracking-wider">Lead Sources</label>
                <div className="grid grid-cols-4 gap-2 p-3 bg-slate-50 border border-slate-200 rounded-xl">
                  {['Website', 'Facebook', 'Instagram', 'Google Ads', 'LinkedIn', 'WhatsApp', 'Referral', 'Manual Import'].map((src) => {
                    const isSelected = newCampaign.sources?.includes(src) || false;
                    return (
                      <label
                        key={src}
                        className={`flex items-center gap-2 p-2 rounded-lg border cursor-pointer select-none text-[11px] font-semibold transition-all ${
                          isSelected
                            ? 'bg-blue-50 border-blue-200 text-blue-700 shadow-xs'
                            : 'bg-white border-slate-200 text-slate-600 hover:bg-slate-50'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={() => {
                            const current = newCampaign.sources || [];
                            const updated = current.includes(src)
                              ? current.filter(s => s !== src)
                              : [...current, src];
                            setNewCampaign({ ...newCampaign, sources: updated });
                          }}
                          className="w-3.5 h-3.5 accent-blue-600 rounded text-blue-600 cursor-pointer"
                        />
                        {src}
                      </label>
                    );
                  })}
                </div>
              </div>

              {/* Lead Assignment Rules */}
              <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/60 space-y-2">
                <span className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider block">Lead Assignment Rules (HubSpot / Salesforce style)</span>
                <div className="grid grid-cols-1 gap-4">
                  <div>
                    <label className="text-[9px] font-bold text-slate-400 block mb-1">Distribution Method</label>
                    <select
                      value={newCampaign.assignment}
                      onChange={(e) => setNewCampaign({ ...newCampaign, assignment: e.target.value })}
                      className="w-full h-8 px-2 border border-slate-200 rounded-lg bg-white text-[11px] font-semibold cursor-pointer"
                    >
                      <option value="Round Robin Distribution">Round Robin Distribution</option>
                      <option value="Auto Assign to Sales Team A">Auto Assign to Sales Team A</option>
                      <option value="Auto Assign to Sales Team B">Auto Assign to Sales Team B</option>
                      <option value="Manual Assignment">Manual Assignment</option>
                    </select>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex justify-end gap-2.5 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setActiveTab('ALL_CAMPAIGNS')}
                  className="px-4 py-2 border border-slate-250 hover:bg-slate-100 text-slate-700 rounded-xl text-xs font-bold transition-all cursor-pointer animate-duration-150"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold transition-all cursor-pointer shadow-sm"
                >
                  Launch Campaign
                </button>
              </div>

            </form>
          </div>
        )}

        {activeTab === 'DETAILS' && (
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 text-left">
            
            {/* Campaign Sidebar Selector */}
            <div className="lg:col-span-1 bg-white border border-slate-200 rounded-2xl p-4 shadow-2xs space-y-3">
              <h3 className="text-xs font-black text-slate-400 uppercase tracking-wider">Select Campaign</h3>
              <div className="space-y-1">
                {campaigns.map(c => (
                  <button
                    key={c.id}
                    onClick={() => setSelectedCampaignId(c.id)}
                    className={`w-full px-3 py-2 text-xs font-bold rounded-lg text-left transition-all ${
                      selectedCampaignId === c.id
                        ? 'bg-blue-50 text-blue-700 border border-blue-100'
                        : 'text-slate-650 hover:bg-slate-50'
                    }`}
                  >
                    <span className="block truncate font-bold">{c.name}</span>
                    <span className="text-[9px] text-slate-400 font-semibold block mt-0.5">{c.type}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Campaign Details Content Area */}
            <div className="lg:col-span-3 space-y-4">
              
              {/* Campaign Header Profile */}
              <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                  <span className="text-[9.5px] font-extrabold text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-100/30 uppercase tracking-wider">{activeCampaign.type}</span>
                  <h2 className="text-base font-extrabold text-slate-800 mt-1">{activeCampaign.name}</h2>
                  <p className="text-[11px] text-slate-400 font-medium mt-0.5">{activeCampaign.description}</p>
                </div>
                <div className="flex bg-slate-100 rounded-xl p-0.5 border border-slate-200 shrink-0">
                  {[
                    { id: 'OVERVIEW', label: 'Overview' },
                    { id: 'LEADS', label: 'Leads' },
                    { id: 'ACTIVITIES', label: 'Activities' },
                    { id: 'ANALYTICS', label: 'Analytics' }
                  ].map(sub => (
                    <button
                      key={sub.id}
                      onClick={() => setDetailsSubTab(sub.id)}
                      className={`px-3 py-1 text-[10.5px] font-extrabold rounded-lg transition-all cursor-pointer ${
                        detailsSubTab === sub.id ? 'bg-white shadow-2xs text-slate-850 font-black' : 'text-slate-500 hover:text-slate-800'
                      }`}
                    >
                      {sub.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Sub-tab view contents */}
              <div className="w-full">
                
                {detailsSubTab === 'OVERVIEW' && (
                  <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs grid grid-cols-2 gap-4">
                    <div>
                      <span className="text-[9px] font-extrabold text-slate-400 block uppercase tracking-wider mb-1">Campaign Owner</span>
                      <strong className="text-slate-800 text-[12.5px]">{activeCampaign.owner}</strong>
                    </div>
                    <div>
                      <span className="text-[9px] font-extrabold text-slate-400 block uppercase tracking-wider mb-1">Timeline Dates</span>
                      <strong className="text-slate-850 text-[12.5px] font-mono">{activeCampaign.startDate} to {activeCampaign.endDate || 'Ongoing'}</strong>
                    </div>
                    <div>
                      <span className="text-[9px] font-extrabold text-slate-400 block uppercase tracking-wider mb-1">Source Mapping</span>
                      <strong className="text-slate-800 text-[12.5px]">{activeCampaign.mapping}</strong>
                    </div>
                    <div>
                      <span className="text-[9px] font-extrabold text-slate-400 block uppercase tracking-wider mb-1">Assignment Rule</span>
                      <strong className="text-slate-800 text-[12.5px]">{activeCampaign.assignment}</strong>
                    </div>
                  </div>
                )}

                {detailsSubTab === 'LEADS' && (
                  <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-xs">
                    <table className="w-full border-collapse">
                      <thead>
                        <tr className="border-b border-slate-200 bg-slate-50/50 text-[10px] font-bold text-slate-500 uppercase tracking-wider select-none text-center">
                          <th className="px-4 py-2.5 text-left">Lead Name</th>
                          <th className="px-4 py-2.5">Email</th>
                          <th className="px-4 py-2.5">Pipeline Status</th>
                          <th className="px-4 py-2.5">Assigned Agent</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-150 text-[12px] font-sans">
                        {initialLeadsList
                          .filter(l => l.campaignId === activeCampaign.id || activeCampaign.id === 'CMP-001') // fallback mock filtering
                          .map((lead, idx) => (
                            <tr key={idx} className="hover:bg-slate-50/30">
                              <td className="px-4 py-2.5 font-bold text-slate-700">{lead.name}</td>
                              <td className="px-4 py-2.5 text-center text-slate-500 font-mono">{lead.email}</td>
                              <td className="px-4 py-2.5 text-center">
                                <span className={`inline-block px-1.5 py-0.5 rounded text-[8.5px] font-bold ${
                                  lead.status === 'Converted' ? 'bg-green-50 text-green-700' :
                                  lead.status === 'Qualified' ? 'bg-indigo-50 text-indigo-700' :
                                  'bg-slate-100 text-slate-600'
                                }`}>{lead.status}</span>
                              </td>
                              <td className="px-4 py-2.5 text-center text-slate-600">{lead.assignedTo}</td>
                            </tr>
                          ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {detailsSubTab === 'ACTIVITIES' && (
                  <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
                    {/* Add note form */}
                    <form onSubmit={handleAddActivity} className="flex gap-2">
                      <input
                        type="text"
                        value={newNote}
                        onChange={(e) => setNewNote(e.target.value)}
                        placeholder="Log notes, tasks, or follow-ups here..."
                        className="flex-1 h-8 px-2.5 border border-slate-200 rounded-lg bg-slate-50 text-[11px] outline-none focus:bg-white focus:border-blue-500"
                      />
                      <button
                        type="submit"
                        className="px-3 bg-blue-650 hover:bg-blue-700 text-white rounded-lg text-xs font-bold transition-colors cursor-pointer"
                      >
                        Add Entry
                      </button>
                    </form>

                    {/* Timeline activities */}
                    <div className="space-y-3.5 pt-2">
                      {activities
                        .filter(a => a.campaignId === activeCampaign.id)
                        .map((act) => (
                          <div key={act.id} className="border-l-2 border-blue-500 pl-4 py-1 flex items-start gap-3">
                            <div className="flex-1">
                              <div className="flex justify-between items-center text-[10px]">
                                <strong className="text-slate-700 font-bold">{act.user} ({act.type})</strong>
                                <span className="text-slate-400 font-mono">{act.date} {act.time}</span>
                              </div>
                              <p className="text-[12px] text-slate-600 mt-1 leading-relaxed">{act.text}</p>
                            </div>
                          </div>
                        ))}
                    </div>
                  </div>
                )}

                {detailsSubTab === 'ANALYTICS' && (
                  <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs grid grid-cols-2 gap-4">
                    <div className="border border-slate-200 rounded-xl p-4 text-center">
                      <span className="text-[8.5px] font-bold text-slate-400 uppercase tracking-wider block">Lead Conversion Efficiency</span>
                      <strong className="text-2xl font-black text-blue-600 mt-1 block">
                        {((activeCampaign.convertedLeads / (activeCampaign.leads || 1)) * 100).toFixed(1)}%
                      </strong>
                    </div>
                    <div className="border border-slate-200 rounded-xl p-4 text-center">
                      <span className="text-[8.5px] font-bold text-slate-400 uppercase tracking-wider block">Avg Cost Per Conversion</span>
                      <strong className="text-2xl font-black text-green-600 mt-1 block">
                        ${(activeCampaign.budget / (activeCampaign.convertedLeads || 1)).toFixed(0)}
                      </strong>
                    </div>
                  </div>
                )}

              </div>

            </div>

          </div>
        )}

        {activeTab === 'REPORTS' && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs text-left space-y-6">
            <div>
              <h2 className="text-md font-bold text-slate-800">Campaigns Performance & ROI Report</h2>
              <p className="text-[11.5px] text-slate-400 mt-0.5">Rolled-up statistics, financial summaries, and team allocations.</p>
            </div>

            {/* Cost vs Conversion table */}
            <div className="border border-slate-200 rounded-xl overflow-hidden">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="border-b border-slate-200 bg-slate-50 text-[10.5px] font-bold text-slate-550 uppercase select-none text-center">
                    <th className="px-4 py-2.5 text-left">Campaign Program</th>
                    <th className="px-4 py-2.5">Total Cost</th>
                    <th className="px-4 py-2.5">Leads Ingested</th>
                    <th className="px-4 py-2.5">Avg CPL</th>
                    <th className="px-4 py-2.5">Conversions</th>
                    <th className="px-4 py-2.5">Estimated ROI</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-150 text-[12px] font-sans">
                  {campaigns.map((c, idx) => {
                    const cpl = c.leads > 0 ? c.budget / c.leads : 0
                    const roi = c.budget > 0 ? ((c.convertedLeads * 1500 - c.budget) / c.budget) * 100 : 0
                    return (
                      <tr key={idx} className="hover:bg-slate-50/20">
                        <td className="px-4 py-2.5 font-bold text-slate-750">{c.name}</td>
                        <td className="px-4 py-2.5 text-center font-mono font-semibold">${c.budget.toLocaleString()}</td>
                        <td className="px-4 py-2.5 text-center font-mono font-bold text-slate-800">+{c.leads}</td>
                        <td className="px-4 py-2.5 text-center font-mono text-slate-650">${cpl.toFixed(1)}</td>
                        <td className="px-4 py-2.5 text-center font-mono font-bold text-green-600">+{c.convertedLeads}</td>
                        <td className={`px-4 py-2.5 text-center font-mono font-extrabold ${roi > 0 ? 'text-green-600' : 'text-slate-500'}`}>{roi.toFixed(0)}%</td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>

            <div className="flex justify-end pt-2 border-t border-slate-100">
              <ExportButton triggerToast={triggerToast} />
            </div>
          </div>
        )}
      </div>

    </div>
  )
}
